finished, but curious about how to make variables truly private
danieltichiyama/js-zombies pull request #2
Opened 2019-07-23 04:00 UTC by danieltichiyama

2019-07-25 01:11 UTC, taesup requested changes

2019-07-25 01:11 UTC, taesup commented on zombies.js
> +  Item.call(this, name);
The `item.call` should be above the `this.damage`

2019-07-25 01:11 UTC, taesup commented on zombies.js
> +  Item.call(this, name);
Move the Item.call one line up.

2019-07-25 01:11 UTC, taesup commented on zombies.js
> +  this._pack = [];
`_pack and _maxHealth` should be private variables by using const instead of this.

2019-07-25 01:11 UTC, taesup commented on zombies.js
> +  }
Same comment about the last two if statements begin joined together.

2019-07-25 01:11 UTC, taesup commented on zombies.js
> +  if (this.getPack().indexOf(item) !== -1) {
Same comment about putting the index into a variable here.

2019-07-27 20:02 UTC, taesup requested changes

2019-07-27 20:02 UTC, taesup commented on zombies.js
> +  this._maxHealth = health;
This should be a const.

2019-07-27 20:25 UTC, danieltichiyama commented on zombies.js
> +  this._maxHealth = health;
changes made, ready for review.

2019-07-27 21:05 UTC, taesup approved these changes

2019-07-27 21:07 UTC, merged